package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /mnt/hgfs/eclipse-workspace/CORBA-HelloWorld/resources/Hello.idl
* Wednesday, January 9, 2019 10:50:36 PM CET
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
